### ISSUE TITLE
Floating above bike in first person / how to recenter?

### ISSUE THREAD

**Issue by Hoshi82** [Holydh/Descenders_VRmod#1]
Mod starts and runs fine but the camera is about 2 meter to high above the bike. In first person espeacially. Also I don't face forward and using recenter in SteamVR repositions me but not in the correct direction. Also I am still way above the bike. Looked for a config or something but couldn't find anything. Is there a way to reset camera and recenter?

Using a Valve Index

**Comment by Holydh** [comment]
You can now download and install the new version (v1.0.2) to fix this issue for SteamVR hmds.
You can also use https://store.steampowered.com/app/1009850/OVR_Advanced_Settings/ to fine tune your position (in the offset tab of the tool)

**Comment by Holydh** [comment]
I'm closing this issue but feel free to reopen it if the new version doesn't fix it.

**Comment by dravpin** [comment]
Im having this same issue ovr is fine but then the hud cant be seen
